runtime: go111
default_expiration: "14d"

handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /images
  static_dir: images

- url: /.*
  script: auto
